// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// This plugin's OWN CUE schema — the typed plugin_input for the `wl`
// live-container check verb, served over the Describe channel. It is the SINGLE
// SOURCE for this plugin's params, used two ways (the same contract core `spec`
// and the reference plugin-http use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a TYPED
//     struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the host splices this source onto the
//     base (base ++ plugin) and validates every authored `wl` step's plugin_input
//     against #WlInput.
//
// Every wl-EXCLUSIVE field lives here (they left core #Op in the schema-compaction
// cutover): the verb `method` enum (the former core #WlMethod, 38 methods incl. the
// overlay-*/sway-* nested ones) plus the input/window/artifact modifiers
// (x/y/x2/y2/button/direction/amount/target/text/key/combo/action/query/command +
// artifact/artifact_min_bytes/artifact_min_dimensions/artifact_not_uniform).
// `command` — the argv for `exec` / `sway-msg` — is ABSORBED from the former shared
// #Op command modifier (the residual #Op `command` field is the command plugin's
// internal rehydration target, never wl's). The step's shared modifiers stay on
// #Op, read off the marshalled step Op: the exit_status/stdout/stderr matchers
// (sdk.VerbVerdict).
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone (gengotypes +
// the SDK's serve-side check) AND splices onto the base (base ++ plugin is a
// def-name collision check, not a base-reference resolver).
type WlInput struct {
	// method — the wl verb method (the former core #WlMethod enum).
	Method string `yaml:"method,omitempty" json:"method"`

	// x/y — desktop-absolute pointer coordinates (click/double-click/mouse/scroll/drag).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// x2/y2 — the drag end coordinates.
	X2 int `yaml:"x2,omitempty" json:"x2,omitempty"`

	Y2 int `yaml:"y2,omitempty" json:"y2,omitempty"`

	// button — pointer button (left/right/middle; empty defaults to left).
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// text — text to type / the clipboard payload / the overlay text / the exec-adjacent text.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// key — a named XKB key for `key` (wtype -k).
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// combo — a key combination for `key-combo` (e.g. ctrl+shift+t).
	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	// direction — scroll direction (up/down/left/right).
	Direction string `yaml:"direction,omitempty" json:"direction,omitempty"`

	// amount — scroll step count (0 defaults to 3).
	Amount int `yaml:"amount,omitempty" json:"amount,omitempty"`

	// target — the window/output/workspace target (focus/close/fullscreen/minimize/
	// geometry/xprop/overlay name/resolution WxH/sway-* argument).
	Target string `yaml:"target,omitempty" json:"target,omitempty"`

	// action — the sub-action selector (atspi tree/find/click; clipboard get/set/clear).
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// query — the atspi find/click element query (name / role / "name:role").
	Query string `yaml:"query,omitempty" json:"query,omitempty"`

	// command — the argv for `exec` / `sway-msg` (absorbed from the former shared
	// #Op command modifier).
	Command string `yaml:"command,omitempty" json:"command,omitempty"`

	// artifact — the host path a `screenshot` writes its PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes — assert the artifact is at least N bytes.
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	// artifact_min_dimensions — assert the decoded image is at least WxH.
	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	// artifact_not_uniform — assert the image is not uniformly one color.
	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`
}
